# Generated by Django 2.0 on 2017-12-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_staff'),
        ('accounts', '0002_auto_20171208_1625'),
    ]

    operations = [
    ]
