# Generated by Django 2.0 on 2017-12-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20171208_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='id',
        ),
        migrations.AlterField(
            model_name='credential',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
    ]
