# Generated by Django 2.0 on 2017-12-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
